vars:
  - params.json

stages:
  fetch_data_pol_subjects:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.subjects}"
      -o "${dvc_root}${data.interim_data.pol.subjects}"
    deps:
      - ${dvc_root}${data.raw_data.pol.subjects}
    outs:
      - ${dvc_root}${data.interim_data.pol.subjects}
    wdir: ${dvc_root}${wdir.fetch_data}
  fetch_data_pol_scolarship:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.scholarship}"
      -o "${dvc_root}${data.interim_data.pol.scholarship}"
    deps:
      - ${dvc_root}${data.raw_data.pol.scholarship}
    outs:
      - ${dvc_root}${data.interim_data.pol.scholarship}
    wdir: ${dvc_root}${wdir.fetch_data}
  fetch_data_pol_personal_data:
    cmd: >-
      python3 ${dvc_root}${scripts.fetch_data}
      -i "${dvc_root}${data.raw_data.pol.personal_data}"
      -o "${dvc_root}${data.interim_data.pol.personal_data}"
    deps:
      - ${dvc_root}${data.raw_data.pol.personal_data}
    outs:
      - ${dvc_root}${data.interim_data.pol.personal_data}
    wdir: ${dvc_root}${wdir.fetch_data}
  etl_pol_subjects:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.scolarship_&_subjects}
      -i "${dvc_root}${data.interim_data.pol.subjects}"
      -o "${dvc_root}${data.processed_data.pol.subjects}"
    deps:
      - ${dvc_root}${data.interim_data.pol.subjects}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.subjects}
    wdir: ${dvc_root}${wdir.etl.scolarship_&_subjects}
  etl_pol_scolarship:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.scolarship_&_subjects}
      -i "${dvc_root}${data.interim_data.pol.scholarship}"
      -o "${dvc_root}${data.processed_data.pol.scholarship}"
    deps:
      - ${dvc_root}${data.interim_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.scholarship}
    wdir: ${dvc_root}${wdir.etl.scolarship_&_subjects}
  etl_pol_personal_data:
    cmd: >-
      python3 ${dvc_root}${scripts.etl.personal_data}
      -i "${dvc_root}${data.interim_data.pol.personal_data}" "${dvc_root}${data.processed_data.pol.subjects}"
      -o "${dvc_root}${data.processed_data.pol.personal_data}"
    deps:
      - ${dvc_root}${data.interim_data.pol.personal_data}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.processed_data.pol.personal_data}
    wdir: ${dvc_root}${wdir.etl.personal_data}
  feat_eng_pol_personal_data:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.personal_data_script}
      -i "${dvc_root}${data.processed_data.pol.personal_data}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.personal_data.pol}"
    deps:
      - ${dvc_root}${data.processed_data.pol.personal_data}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.personal_data.pol}
    wdir: ${dvc_root}${wdir.feat_eng.personal_data_script}
  feat_sel_pol_personal_data:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.personal_data.pol}"
      -o "${dvc_root}${data.final_analys_data.personal_data.pol}"
      -c 0
      -q 0
    deps:
      - ${dvc_root}${data.analys_data.personal_data.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.personal_data.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analysis_pol_personal_data_ensemble:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_personal_data_ensemble}
#      -i "${dvc_root}${data.final_analys_data.personal_data.pol}"
#      -o "${dvc_root}${data.analys_data.personal_data.pol}"
#      -c 0
#      -q 0
#      -mn "1st_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.personal_data.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.personal_data.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" 
      "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.1st_quad.pol}"
      -c 1
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.personal_data.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_1st_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.1st_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.1st_quad.pol}"
      -c 1
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.1st_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.1st_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analysis_pol_1st_quad_ensemble:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.1st_quad.pol}"
#      -o "${dvc_root}${data.analys_data.1st_quad.pol}"
#      -c 1
#      -q 1
#      -mn "2nd_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.1st_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.1st_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_2nd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" 
      "${dvc_root}${data.processed_data.pol.subjects}" 
      "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.2nd_quad.pol}"
      -c 1
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.personal_data.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.2nd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_2nd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.2nd_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.2nd_quad.pol}"
      -c 1
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.2nd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.2nd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_2nd_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.2nd_quad.pol}"
#      -o "${dvc_root}${data.analys_data.2nd_quad.pol}"
#      -c 1
#      -q 2
#      -mn "3rd_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.2nd_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.2nd_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_3rd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.3rd_quad.pol}"
      -c 2
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.2nd_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.3rd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_3rd_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.3rd_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.3rd_quad.pol}"
      -c 2
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.3rd_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.3rd_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_3rd_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.3rd_quad.pol}"
#      -o "${dvc_root}${data.analys_data.3rd_quad.pol}"
#      -c 2
#      -q 1
#      -mn "4th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.3rd_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.3rd_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_4th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.4th_quad.pol}"
      -c 2
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.3rd_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.4th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_4th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.4th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.4th_quad.pol}"
      -c 2
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.4th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.4th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_4th_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.4th_quad.pol}"
#      -o "${dvc_root}${data.analys_data.4th_quad.pol}"
#      -c 2
#      -q 2
#      -mn "5th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.4th_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.4th_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_5th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.5th_quad.pol}"
      -c 3
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.4th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.5th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_5th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.5th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.5th_quad.pol}"
      -c 3
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.5th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.5th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_5th_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.5th_quad.pol}"
#      -o "${dvc_root}${data.analys_data.5th_quad.pol}"
#      -c 3
#      -q 1
#      -mn "6th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.5th_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.5th_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_6th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.6th_quad.pol}"
      -c 3
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.5th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.6th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_6th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.6th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.6th_quad.pol}"
      -c 3
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.6th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.6th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_6th_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.6th_quad.pol}"
#      -o "${dvc_root}${data.analys_data.6th_quad.pol}"
#      -c 3
#      -q 2
#      -mn "7th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.6th_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.6th_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_7th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.7th_quad.pol}"
      -c 4
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.6th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.7th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_7th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.7th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.7th_quad.pol}"
      -c 4
      -q 1
    deps:
      - ${dvc_root}${data.analys_data.7th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.7th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_7th_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.7th_quad.pol}"
#      -o "${dvc_root}${data.analys_data.7th_quad.pol}"
#      -c 4
#      -q 1
#      -mn "8th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.7th_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.7th_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
  feat_eng_pol_8th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_eng.quadrimesters_script}
      -i "${dvc_root}${data.analys_data.personal_data.pol}" "${dvc_root}${data.processed_data.pol.subjects}" "${dvc_root}${data.processed_data.pol.scholarship}"
      -o "${dvc_root}${data.analys_data.8th_quad.pol}"
      -c 4
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.7th_quad.pol}
      - ${dvc_root}${data.processed_data.pol.subjects}
      - ${dvc_root}${data.processed_data.pol.scholarship}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.analys_data.8th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_eng.quadrimesters_script}
  feat_sel_pol_8th_quad:
    cmd: >-
      python3 ${dvc_root}${scripts.feat_sel}
      -i "${dvc_root}${data.analys_data.8th_quad.pol}"
      -o "${dvc_root}${data.final_analys_data.8th_quad.pol}"
      -c 4
      -q 2
    deps:
      - ${dvc_root}${data.analys_data.8th_quad.pol}
      - ${dvc_root}/Code/keys.py
    outs:
      - ${dvc_root}${data.final_analys_data.8th_quad.pol}
    wdir: ${dvc_root}${wdir.feat_sel}
#  analys_pol_8th_quad:
#    cmd: >-
#      python3 ${dvc_root}${scripts.analys_quadrimesters_ensemble}
#      -i "${dvc_root}${data.final_analys_data.8th_quad.pol}"
#      -o "${dvc_root}${data.analys_data.8th_quad.pol}"
#      -c 4
#      -q 2
#      -mn "9th_model"
#    deps:
#      - ${dvc_root}${data.final_analys_data.8th_quad.pol}
#      - ${dvc_root}/Code/keys.py
#    outs:
#      - ${dvc_root}${data.analys_data.8th_quad.pol}
#    wdir: ${dvc_root}${wdir.analys}
